version: "3.6"
networks:
    noharm-net:
      name: noharm-net
      ipam:
        driver: default
        config: 
          - subnet: "172.19.0.0/16"
volumes:
  nifi_conf:
services:
 nifi:
    container_name: "noharm-nifi"
    hostname: "noharm-nifi"
    image: "apache/nifi:latest"
    entrypoint: ["bash", "-c", "/opt/nifi/scripts/ext/update_nifi.sh; /opt/nifi/scripts/start.sh"]
    env_file:
      - ./noharm.env
    ipc: "private"
    labels:
        maintainer: "NoHarm.ai <suporte@noharm.ai>"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      noharm-net:
        ipv4_address: 172.19.0.2
    ports:
      - "8443:8443/tcp"
    restart: "always"
    user: "nifi"
    working_dir: "/opt/nifi/nifi-current"
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - ./:/opt/nifi/scripts/ext/
 myanony:
    container_name: "noharm-anony"
    hostname: "noharm-anony"
    image: "noharm/anony:latest"
    env_file:
      - ./noharm.env    
    ipc: "private"
    labels:
      maintainer: "NoHarm.ai <suporte@noharm.ai>"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      noharm-net:
        ipv4_address: 172.19.0.3
    ports:
      - "80:80/tcp"
    restart: "always"
    working_dir: "/app"
 mygetname:
    container_name: "noharm-getname"
    hostname: "noharm-getname"
    image: "noharm/getname:latest"
    env_file:
      - ./noharm.env    
    ipc: "private"
    labels:
      maintainer: "NoHarm.ai <suporte@noharm.ai>"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      noharm-net:
        ipv4_address: 172.19.0.4
    ports:
      - "443:443/tcp"
    restart: "always"
    working_dir: "/app"
 nifi-toolkit:
    container_name: "nifi-toolkit"
    image: "apache/nifi-toolkit:latest"
    user: root
    networks:
      noharm-net:
        ipv4_address: 172.19.0.5
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
    #entrypoint: ["bash", "-c", "/opt/nifi-toolkit/*/bin/tls-toolkit.sh standalone -n noharm-nifi -f /opt/nifi/nifi-current/conf/nifi.properties -o /opt/nifi/nifi-current/conf/ --isOverwrite -P 4bc73749cca686a5ba87a20400d3e357 -K d4d0df4c643c6ea4ada70451c0c7d950 -S d4d0df4c643c6ea4ada70451c0c7d950 ; chown -R nifi:nifi /opt/nifi/nifi-current/conf/"]
